version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 app:app --workers 3 --threads 2 --timeout 120"

volumes:
  db_data: