"""Adicionado campos de autoavaliacao

Revision ID: 00b17b0d9bfc
Revises: 095ae1cd49f8
Create Date: 2024-09-12 01:41:21.928966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b17b0d9bfc'
down_revision = '095ae1cd49f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_nota_rendimento', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_facilidade_e_compreensao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_conhecimentos_tecnicos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_organizacao_metodo_trabalho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_iniciativa_independencia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_disciplina', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_sociabilidade_desempenho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_assiduidade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_cooperecao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_nota_responsabilidade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aluno_atividades', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aluno_comentarios', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aluno_media_notas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.drop_column('aluno_media_notas')
        batch_op.drop_column('aluno_comentarios')
        batch_op.drop_column('aluno_atividades')
        batch_op.drop_column('aluno_nota_responsabilidade')
        batch_op.drop_column('aluno_nota_cooperecao')
        batch_op.drop_column('aluno_nota_assiduidade')
        batch_op.drop_column('aluno_nota_sociabilidade_desempenho')
        batch_op.drop_column('aluno_nota_disciplina')
        batch_op.drop_column('aluno_nota_iniciativa_independencia')
        batch_op.drop_column('aluno_nota_organizacao_metodo_trabalho')
        batch_op.drop_column('aluno_nota_conhecimentos_tecnicos')
        batch_op.drop_column('aluno_nota_facilidade_e_compreensao')
        batch_op.drop_column('aluno_nota_rendimento')

    # ### end Alembic commands ###
