"""Adapt models for Flask-Security

Revision ID: 015d757b1edd
Revises: a4012b591bbb
Create Date: 2024-03-23 17:17:05.423972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015d757b1edd'
down_revision = 'a4012b591bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('active')
        batch_op.drop_column('password')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
