"""Adicionado campos de avaliacao do orientador e banca

Revision ID: 095ae1cd49f8
Revises: fbc78ebc0e13
Create Date: 2024-09-04 01:03:05.057757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095ae1cd49f8'
down_revision = 'fbc78ebc0e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_nota_avaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('professor_avaliacao_comentarios', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_avaliacao_empresa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_avaliacao_orientador', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_apresentacao_oral_1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_pratica_profissional_1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_relatorio_1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_apresentacao_oral_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_pratica_profissional_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_relatorio_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_avaliador_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banca_avaliador_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banca_autoavaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_aprovado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('banca_reprovado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('banca_aprovado_com_ressalva', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('banca_relatorio_entrega', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('banca_refazer_apresentacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('banca_comentarios', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.drop_column('banca_comentarios')
        batch_op.drop_column('banca_refazer_apresentacao')
        batch_op.drop_column('banca_relatorio_entrega')
        batch_op.drop_column('banca_aprovado_com_ressalva')
        batch_op.drop_column('banca_reprovado')
        batch_op.drop_column('banca_aprovado')
        batch_op.drop_column('banca_autoavaliacao')
        batch_op.drop_column('banca_avaliador_2')
        batch_op.drop_column('banca_avaliador_1')
        batch_op.drop_column('banca_nota_relatorio_2')
        batch_op.drop_column('banca_nota_pratica_profissional_2')
        batch_op.drop_column('banca_nota_apresentacao_oral_2')
        batch_op.drop_column('banca_nota_relatorio_1')
        batch_op.drop_column('banca_nota_pratica_profissional_1')
        batch_op.drop_column('banca_nota_apresentacao_oral_1')
        batch_op.drop_column('banca_nota_avaliacao_orientador')
        batch_op.drop_column('banca_nota_avaliacao_empresa')
        batch_op.drop_column('professor_avaliacao_comentarios')
        batch_op.drop_column('professor_nota_avaliacao')

    # ### end Alembic commands ###
