"""AdicionadoTabelaParaAtividadeDoEstagio

Revision ID: 24c149f81854
Revises: 27d5037ec21a
Create Date: 2024-10-05 15:57:58.952415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c149f81854'
down_revision = '27d5037ec21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades_estagio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('horario_entrada', sa.Time(), nullable=False),
    sa.Column('horario_saida', sa.Time(), nullable=False),
    sa.Column('horas_totais', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('estagio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estagio_id'], ['estagios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividades_estagio')
    # ### end Alembic commands ###
