"""Adicionado mais campos de autoavaliacao

Revision ID: 27d5037ec21a
Revises: 00b17b0d9bfc
Create Date: 2024-09-12 09:46:38.912635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d5037ec21a'
down_revision = '00b17b0d9bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_avaliacao_empresa_condicoes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_atendeu_expectativas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_contribui_formacao_profissional', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_recomendaria_para_outro', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_curso_capacitou', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_orientador_acompanhou', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aluno_avaliacao_supervisor_acompanhou', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.drop_column('aluno_avaliacao_supervisor_acompanhou')
        batch_op.drop_column('aluno_avaliacao_orientador_acompanhou')
        batch_op.drop_column('aluno_avaliacao_curso_capacitou')
        batch_op.drop_column('aluno_avaliacao_recomendaria_para_outro')
        batch_op.drop_column('aluno_avaliacao_contribui_formacao_profissional')
        batch_op.drop_column('aluno_avaliacao_atendeu_expectativas')
        batch_op.drop_column('aluno_avaliacao_empresa_condicoes')

    # ### end Alembic commands ###
