"""Add_IsApproved_To_Aluno

Revision ID: 33dd0275c201
Revises: 57b6be0786ce
Create Date: 2024-07-12 16:10:12.538046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dd0275c201'
down_revision = '57b6be0786ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
