"""Add password hash to user model

Revision ID: 537f99fb742b
Revises: d8e42accd485
Create Date: 2024-03-17 23:50:02.865643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537f99fb742b'
down_revision = 'd8e42accd485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
