"""AddMissingFieldsOnAta

Revision ID: 5a062212cb4b
Revises: 24c149f81854
Create Date: 2024-10-25 23:45:21.982165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a062212cb4b'
down_revision = '24c149f81854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banca_nota_apresentacao_oral_supervisor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_pratica_profissional_supervisor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banca_nota_relatorio_supervisor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estagios', schema=None) as batch_op:
        batch_op.drop_column('banca_nota_relatorio_supervisor')
        batch_op.drop_column('banca_nota_pratica_profissional_supervisor')
        batch_op.drop_column('banca_nota_apresentacao_oral_supervisor')

    # ### end Alembic commands ###
