"""Email do Professor nao unico

Revision ID: 8679e235d5bb
Revises: 8da09e673a60
Create Date: 2024-05-25 17:30:59.046795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8679e235d5bb'
down_revision = '8da09e673a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_constraint('professores_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_unique_constraint('professores_email_key', ['email'])

    # ### end Alembic commands ###
